# Overrides for production environment
baseurl = "https://h-enk.github.io/doks-gh-pages/"
canonifyURLs = true

[outputFormats.searchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true
  notAlternative = true
  path = "doks-gh-pages"
